package booksage;
// Generated 27 ���. 2018 17:03:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Authors generated by hbm2java
 */
public class Authors  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private Date age;
     private Set bookses = new HashSet(0);

    public Authors() {
    }

	
    public Authors(String firstName, String lastName, Date age) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.age = age;
    }
    public Authors(String firstName, String lastName, Date age, Set bookses) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.age = age;
       this.bookses = bookses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getAge() {
        return this.age;
    }
    
    public void setAge(Date age) {
        this.age = age;
    }
    public Set getBookses() {
        return this.bookses;
    }
    
    public void setBookses(Set bookses) {
        this.bookses = bookses;
    }
}


